version: "3.9"
services:
  simple-aja:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    env_file:
      - ./.env.local
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: simple
      POSTGRES_PASSWORD: aja
      POSTGRES_DB: simple_aja_db

      

volumes:
  postgres_data:
